<link href="https://fonts.googleapis.com/css?family=Itim|Rock+Salt" rel="stylesheet"> 
<link href="../assets/css/neophite.css" rel="stylesheet" type="text/css"/>
<h1>Culture du monde biker</h1>
<div class="container">
    <div class="row spaceText">
        <div class="col-md-12 textNeophite">  
            <h2 class="titleNeophite text-center">Un peu de culture...</h2>
            <p>
                Comme toute organisation, tout est codé, codifié, et il y a les droits et les devoirs... D'ailleurs au lendemain de la guerre, les démobilisés se sont retrouvés sans rien ni considération.... et beaucoup ont cherchés à retrouver ce qu ils avaient dans l'armée: Du respect D'ailleurs, le nom de Hells Angels existait déjà dans les clubs militaires depuis la 1ère pendant laquelle une escadrille portait ce nom. Dans les années 20 à Detroit un club affilié à l'A.M.A. idem. Aussi dans les années 30 et 40 avec un groupe d'aviateurs acrobatiques. Pendant la 2ème guerre mondiale plusieurs groupes d'aviateur utilisaient ce nom notamment la 358ème escadrille de bombardiers de l'American Air Force stationnée en Angleterre et un escadron des Flying Tigers en Birmanie. Greg Boyington dit Pappy en faisait partie, ses exploits romancés ont été relatés dans la célèbre série télévisée "les têtes brûlées". On dénombre dans le monde environ 1500 gangs de motards, chaque membre traitant environ une quinzaine de personnes.
            </p>
        </div>
    </div>
        <div class="row spaceText">    
            <div class="col-md-12 textNeophite">  
                <h2 class="titleNeophite text-center">HISTORIQUE</h2>
                <p>
                    L'A.M.A. (American Motorcycle Association) se crée en 1924 et devient le bras organisateur des fabricants de motos et principal support pour en promouvoir la pratique aux U.S.A. Le 4 juillet 1947 à HOLLISTER (U.S.A.) Californie du Sud, des courses motos de dirt et hill-climbing sont organisées par l'A.M.A. pour célébrer l'Indépendance Day. Environ 4000 motards présents. Des échauffourées et désordres occasionnés par une minorité de motards + ou - en état d'ivresse se produisent dans le centre ville et les bars. Ces groupes de motards hirsutes, barbus, tatoués sur des engins puissants, trafiqués et bruyants :HARLEY / INDIAN / NORTON / B.S.A. / TRIUMPH /ARIEL.....refusaient en général le règlement sportif de l'A.M.A. trop sage à leurs yeux et organisaient leurs propres courses " hors la loi " (outlaws) pour se défouler. Ces clubs aux noms bizarres ou évocateurs (en France nous ne sommes pas en reste avec des Bouffe Bitumes, Gueules à Mousse, Noirs talons, Gencives de porc, Barjots, Bielles déglinguées, Mange Bitume, Gorets, Mouches Crevées, Cinglés…..sans être pour autant des 1%) Boozefighters ; traduire ivrognes-bagarreurs ou buveurs de choc, Satans Sinners : les Pêcheurs de Satan, Pissed Off Bastards of Bloomington (POBOB) traduction littérale : Plein le Cul, Les Bâtards de Bloomington, certains deviendront plus tard les premiers Hells Angels...
                </p>
                <p>
                    En réalité dès les années 30, certains clubs se qualifiaient déjà de "outlaws" mais c'est surtout après la seconde guerre mondiale que l'histoire des clubs 1% débute. En effet avec la démobilisation des GI, marins et surtout aviateurs, un certain nombre d'ex militaires ne supportèrent pas de retrouver la normalité grise de la vie civile. Quelle déception, pendant le temps passé sous les drapeaux certains pilotaient ou avaient des responsabilités à bord de bombardiers, chasseurs, chars, porte-avions sous-marins et avaient eu une période de vie aventureuse et très risquée, ce qui après tout était l'apanage de cette jeunesse dont leur gouvernement (et les évènements) avait fait des militaires victorieux. Le contraste était trop grand, le phénomène se reproduira après les guerres de Corée et du Vietnam. Tout naturellement, à leur démobilisation et munis d'un pécule la moto fût l'exutoire de certains, pour d'autres la voiture et certainement aussi d'autres pratiques toutes aussi risquées comme l'abus d'alcool, de drogues ou mener une vie marginale. Dans l'Amérique puritaine d'après-guerre (elle l'est toujours), l'A.M.A. déclare alors que 99% des motards sont "de gentils motocyclistes". Pour cette fédération de fabricants de motos (très attentifs à leur image de marque), cela signifie participer au concours de la plus belle moto, de la mieux équipée, du plus beau couple, de celui qui est le mieux habillé, en fait tout ce qui ressemble quelque peu à une fête de patronage et dont on peut reconnaître que tout cela fait très gnan-gnan. Cette déclaration mit le feu aux poudres : indigné, le monde des motards non conventionnels ainsi mis au pilori et estampillé dès lors "ennemi public" opte d'emblée et avec fierté pour l'appellation 1% qui symbolise depuis le monde des bikers purs et durs.
                </p>
            </div>
        </div>
        <div class="row spaceText">
            <div class="col-md-12 textNeophite">
                <h2 class="titleNeophite text-center">SIGNES DE RECONNAISSANCE</h2>
                <p>
                    A l'origine les motards appartenant à un club arboraient dans le dos de leur blouson l'emblème de leur club qui était d'une seule pièce.
                </p>
                <p>
                    Dans le but de se distinguer comme un club "hors la loi" par rapport aux autres clubs, les one percenters divisèrent le patch de leur club en 3 parties : 2 rockers et 1 patch central. Les rockers sont en forme de bandeaux incurvés, l'appellation rocker venant de la forme des pieds des rocking chair ou de celle d'une pièce de moteur : le culbuteur, ou rocker. L'ensemble des 3 pièces est aussi appelé "couleurs". Le rocker du haut désigne le nom du club, le centre ou patch l'emblème du club, le rocker du bas la région d'appartenance. Parfois le rocker du bas est basculé sous un des deux bras. La plupart des "couleurs" ont aussi MC imprimé sur le rocker ou un petit patch "cube" distinct. Certains MC autorisent un membre à porter un rocker supérieur ou inférieur (ou même un petit patch) marqué NOMAD qui désigne un motard n'ayant pas de réel domicile fixe et qui se déplace en fonction de ses propres nécessités. Le rocker PROSPECT (prétendant) ou futur membre est porté sur le rocker du bas ou du haut après que son titulaire ait été parrainé part un membre à part entière et approuvé par le club. Evidemment en tant que prospect il ne porte pas en principe le patch principal. C'est seulement lorsque son temps de prospect sera jugé terminé et le vote du club en sa faveur qu'il sera autorisé à avoir les couleurs complètes et être considéré comme un membre à part entière. le terme probationnary est aussi utilisé à la place de prospect. Le rocker HANGARROUND ou associé . Les hangarrounds sont des connaissances des clubs 1%, avec l'espoir de devenir prospect puis membre à part entière. Bien entendu ils ne portent pas de patch central. Pour se démarquer des "gentils motards", les bikers optèrent donc pour le sigle 1%, le port de couleurs (écussons de moto club cousus dans le dos de veste en jean ou en cuir, réminiscence des blousons aviateurs)... D'un point de vue purement artistique, les patchs sont un mélange : de mythes nordiques, BIFROST nom du pont "arc en ciel" entre Asgard et Midgard RAGNAROK: bataille entre Géants et Dieux YGGDRASIL: le frêne géant supportant les 9 mondes le marteau du dieu Thor qui revient dans sa main gantée de fer après avoir été lancé vision artistique d'YGGDRASIL d'éléments du 7ème art hollywoodien, et d'un fort héritage militaire. En particulier l'omniprésente de crânes, ossements, diables, ailes, toons qui ont beaucoup inspirés certains patchs "outlaws" ainsi que d'autres symboles bien sûr comme des croix, épées, dragons, flammes.
                </p>  
            </div>
        </div>
    </div>
</body>
</html>
